version: "3.9"

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: forms_user
      POSTGRES_PASSWORD: forms_pass
      POSTGRES_DB: metrics_db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  db_data:
