version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: ai_forms_postgres
    environment:
      POSTGRES_USER: forms_user
      POSTGRES_PASSWORD: forms_pass
      POSTGRES_DB: forms_db
    volumes:
      - pg_data:/var/lib/postgresql/data
      # - ./init_db_full.sql:/docker-entrypoint-initdb.d/init_db_full.sql
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    command: ["postgres", 
      "-c", "config_file=/etc/postgresql/postgresql.conf",
      "-c", "hba_file=/etc/postgresql/pg_hba.conf"]
    ports:
      - "5433:5432"

  # grafana:
  #   image: grafana/grafana:11.1.0
  #   container_name: code_metrics_grafana
  #   depends_on:
  #     - postgres
  #   environment:
  #     GF_SECURITY_ADMIN_USER: admin
  #     GF_SECURITY_ADMIN_PASSWORD: admin
  #     GF_USERS_ALLOW_SIGN_UP: "false"
  #     GF_PATHS_PROVISIONING: /etc/grafana/provisioning
  #     GF_AUTH_ANONYMOUS_ENABLED: "true"
  #     GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
  #     GF_AUTH_DISABLE_LOGIN_FORM: "true"
  #     GF_SERVER_HTTP_ADDR: 0.0.0.0
  #   volumes:
  #     - ./grafana/provisioning:/etc/grafana/provisioning
  #     - ./grafana/dashboards:/var/lib/grafana/dashboards
  #   ports:
  #     - "3000:3000"

volumes:
  pg_data:


# docker exec -t code_metrics_postgres pg_dump -U metrics_user -d metrics_db > init_db_full.sql

# docker build -t andreyk/code_metrics_postgres -f Dockerfile.postgres .
# docker push andreyk/code_metrics_postgres
# docker build -t andreyk/code_metrics_grafana -f Dockerfile.grafana .
# docker push andreyk/code_metrics_grafana

